---
apiVersion: v1
kind: Service
metadata:
  name: imageproduct
  labels:
    app: imageproduct

spec:
  type: NodePort
  selector:
    app: imageproduct

  ports:
  - protocol: TCP
    port: 8030
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageproduct
spec:
  selector:
    matchLabels:
      app: imageproduct
  replicas: 1
  template:
    metadata:
      labels:
        app: imageproduct
    spec:
      containers:
      - name: imageproduct
        image: asmaeel/imageproduct:latest
        ports:
        - containerPort: 8030
        livenessProbe:
          httpGet:
            path: /health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1
