---
apiVersion: v1
kind: Service
metadata:
  name: imagestock
  labels:
    app: imagestock
spec:
  type: NodePort
  selector:
    app: imagestock
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagestock
spec:
  selector:
    matchLabels:
      app: imagestock
  replicas: 1
  template:
    metadata:
      labels:
        app: imagestock
    spec:
      containers:
      - name: imagestock
        image: asmaeel/imagestock:latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
